name: "test"
on: push

permissions:
  contents: read
  checks: write

env:
  GODOT_VERSION: 4.5.1
  BUILD_DIR: build
  EXPORT_BIN: godot-tbs-framework.test
  LINUX_EXPORT: Linux (Test)

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.5.1
    steps:
      - name: Get Packages
        run: |
          apt update
          apt install -y ssh
      - name: Checkout Framework
        uses: actions/checkout@v6
      - name: Checkout Tests
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.GODOT_TBS_TEMPLATE_ACTIONS }}
          repository: ${{ github.repository_owner }}/godot-tbs-framework-tests
          path: test
      - name: Copy Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mkdir -v -p ~/.config
          cp -R /root/.config/godot ~/.config/godot
          cp -R /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build
        run: |
          mkdir -v -p build
          godot --headless --build-solutions --quit
          godot --headless --export-debug "${LINUX_EXPORT}" "build/${EXPORT_BIN}.x86_64"
      - name: Run
        run: build/${EXPORT_BIN}.x86_64 --headless
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: 'test/report.xml'